import { google } from "googleapis";
import { logger } from "./logger";

const CONNECTORS_HOSTNAME = process.env.REPLIT_CONNECTORS_HOSTNAME;
const REPL_IDENTITY = process.env.REPL_IDENTITY;
const WEB_REPL_RENEWAL = process.env.WEB_REPL_RENEWAL;
const CONNECTION_ID = process.env.GOOGLE_DRIVE_CONNECTION_ID;

export function isDriveConfigured(): boolean {
  return !!(CONNECTORS_HOSTNAME && CONNECTION_ID);
}

async function getAccessToken(): Promise<string> {
  if (!CONNECTORS_HOSTNAME || !CONNECTION_ID) {
    throw new Error("Google Drive connector not configured. Set GOOGLE_DRIVE_CONNECTION_ID.");
  }

  const url = `https://${CONNECTORS_HOSTNAME}/api/v2/connection/${CONNECTION_ID}/token/access`;
  const headers: Record<string, string> = {};
  if (REPL_IDENTITY) headers["X-Replit-Identity"] = REPL_IDENTITY;
  if (WEB_REPL_RENEWAL) headers["X-Replit-WEB-Identity"] = WEB_REPL_RENEWAL;

  const response = await fetch(url, { headers });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to get Drive access token (${response.status}): ${text}`);
  }

  const data = await response.json() as { access_token: string };
  return data.access_token;
}

function getDriveClient(accessToken: string) {
  const auth = new google.auth.OAuth2();
  auth.setCredentials({ access_token: accessToken });
  return google.drive({ version: "v3", auth });
}

export interface DriveUploadInput {
  title: string;
  studentName: string;
  school?: string;
  serviceType: string;
  academicYear?: string;
  agent?: string;
  date?: string;
  templateName?: string;
  fields?: Record<string, string>;
  notes?: string;
}

function buildHtmlContent(input: DriveUploadInput): string {
  const rows = [
    ["Student Name", input.studentName],
    ["School / Institution", input.school || "—"],
    ["Service Type", input.serviceType],
    ["Academic Year", input.academicYear || "—"],
    ["Agent", input.agent || "—"],
    ["Date", input.date || "—"],
    ["Template", input.templateName || "—"],
  ];

  const baseTable = rows
    .map(
      ([label, value]) =>
        `<tr><td style="font-weight:bold;padding:6px 12px;width:180px;background:#f0f4f8;">${label}</td>` +
        `<td style="padding:6px 12px;">${value}</td></tr>`
    )
    .join("");

  const extraFields =
    input.fields && Object.keys(input.fields).length > 0
      ? Object.entries(input.fields)
          .filter(([, v]) => v)
          .map(
            ([k, v]) =>
              `<tr><td style="font-weight:bold;padding:6px 12px;background:#f0f4f8;">${k}</td>` +
              `<td style="padding:6px 12px;">${v}</td></tr>`
          )
          .join("")
      : "";

  const notesSection = input.notes
    ? `<h3 style="color:#003366;">Notes</h3><p style="line-height:1.6;">${input.notes}</p>`
    : "";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1a2332; }
    h1 { color: #003366; border-bottom: 3px solid #008080; padding-bottom: 8px; }
    h2 { color: #003366; margin-top: 32px; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    td { border: 1px solid #dde3ea; vertical-align: top; }
    .footer { margin-top: 48px; font-size: 12px; color: #6b7c93; border-top: 1px solid #dde3ea; padding-top: 12px; }
  </style>
</head>
<body>
  <h1>${input.title}</h1>
  <h2>Document Information</h2>
  <table>${baseTable}${extraFields}</table>
  ${notesSection}
  <div class="footer">
    Generated by MKS Education Service Document Management System &nbsp;|&nbsp;
    ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
  </div>
</body>
</html>`;
}

export interface DriveUploadResult {
  fileId: string;
  fileUrl: string;
  fileName: string;
}

export async function uploadDocumentToDrive(
  input: DriveUploadInput & { title: string }
): Promise<DriveUploadResult> {
  const accessToken = await getAccessToken();
  const drive = getDriveClient(accessToken);

  const fileName = `${input.serviceType} – ${input.studentName} – ${input.date ?? new Date().toISOString().split("T")[0]}`;
  const htmlContent = buildHtmlContent(input);

  const { Readable } = await import("stream");
  const bodyStream = Readable.from([htmlContent]);

  logger.info({ fileName }, "Uploading document to Google Drive");

  const createRes = await drive.files.create({
    requestBody: {
      name: fileName,
      mimeType: "application/vnd.google-apps.document",
    },
    media: {
      mimeType: "text/html",
      body: bodyStream,
    },
    fields: "id,name",
  });

  const fileId = createRes.data.id!;

  await drive.permissions.create({
    fileId,
    requestBody: {
      role: "reader",
      type: "anyone",
    },
  });

  const fileUrl = `https://docs.google.com/document/d/${fileId}/edit`;
  logger.info({ fileId, fileUrl }, "Document uploaded to Google Drive");

  return { fileId, fileUrl, fileName: createRes.data.name ?? fileName };
}
